# fly.toml app configuration file generated for shf-tool-api on 2023-12-28T21:51:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shf-tool-api"
primary_region = "gig"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
